export const CUBIE_LIST = [
    {
        id: "w",
        type: "center",
        coords: { x: 0, y: -1, z: 0 },
        colors: {
            top: "white",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "y",
        type: "center",
        coords: { x: 0, y: 1, z: 0 },
        colors: {
            bottom: "yellow",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "r",
        type: "center",
        coords: { x: -1, y: 0, z: 0 },
        colors: {
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "o",
        type: "center",
        coords: { x: 1, y: 0, z: 0 },
        colors: {
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "b",
        type: "center",
        coords: { x: 0, y: 0, z: 1 },
        colors: {
            front: "blue",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "g",
        type: "center",
        coords: { x: 0, y: 0, z: -1 },
        colors: {
            back: "green",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },

    {
        id: "wbr",
        type: "corner",
        coords: { x: -1, y: -1, z: 1 },
        colors: {
            top: "white",
            front: "blue",
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wbo",
        type: "corner",
        coords: { x: 1, y: -1, z: 1 },
        colors: {
            top: "white",
            front: "blue",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wgo",
        type: "corner",
        coords: { x: 1, y: -1, z: -1 },
        colors: {
            top: "white",
            back: "green",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wgr",
        type: "corner",
        coords: { x: -1, y: -1, z: -1 },
        colors: {
            top: "white",
            left: "red",
            back: "green",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wb",
        type: "edge",
        coords: { x: 0, y: -1, z: 1 },
        colors: {
            top: "white",
            front: "blue",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wo",
        type: "edge",
        coords: { x: 1, y: -1, z: 0 },
        colors: {
            top: "white",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wr",
        type: "edge",
        coords: { x: -1, y: -1, z: 0 },
        colors: {
            top: "white",
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "wg",
        type: "edge",
        coords: { x: 0, y: -1, z: -1 },
        colors: {
            top: "white",
            back: "green",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "og",
        type: "edge",
        coords: { x: 1, y: 0, z: -1 },
        colors: {
            right: "orange",
            back: "green",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "rg",
        type: "edge",
        coords: { x: -1, y: 0, z: -1 },
        colors: {
            left: "red",
            back: "green",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "rb",
        type: "edge",
        coords: { x: -1, y: 0, z: 1 },
        colors: {
            front: "blue",
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "bo",
        type: "edge",
        coords: { x: 1, y: 0, z: 1 },
        colors: {
            front: "blue",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "by",
        type: "edge",
        coords: { x: 0, y: 1, z: 1 },
        colors: {
            front: "blue",
            bottom: "yellow",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "gy",
        type: "edge",
        coords: { x: 0, y: 1, z: -1 },
        colors: {
            back: "green",
            bottom: "yellow",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "ry",
        type: "edge",
        coords: { x: -1, y: 1, z: 0 },
        colors: {
            left: "red",
            bottom: "yellow",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "oy",
        type: "edge",
        coords: { x: 1, y: 1, z: 0 },
        colors: {
            right: "orange",
            bottom: "yellow",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "ybr",
        type: "corner",
        coords: { x: -1, y: 1, z: 1 },
        colors: {
            front: "blue",
            bottom: "yellow",
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "ybo",
        type: "corner",
        coords: { x: 1, y: 1, z: 1 },
        colors: {
            front: "blue",
            bottom: "yellow",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "ygr",
        type: "corner",
        coords: { x: -1, y: 1, z: -1 },
        colors: {
            back: "green",
            bottom: "yellow",
            left: "red",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
    {
        id: "ygo",
        type: "corner",
        coords: { x: 1, y: 1, z: -1 },
        colors: {
            back: "green",
            bottom: "yellow",
            right: "orange",
        },
        originalTransform: "",
        originalCoords: {},
        rotation: "",
        element: null,
    },
];
